apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-admin
  labels:
    app: pg-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-admin
  template:
    metadata:
      labels:
        app: pg-admin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          ports:
            - containerPort: 4002
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-email
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: pg-admin-service
spec:
  selector:
    app: pg-admin
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 80
      nodePort: 30042
  selector:
    app: pg-admin
