apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apollo-gateway
  template:
    metadata:
      labels:
        app: apollo-gateway
    spec:
      containers:
      - name: apollo-gateway
        image: mahmoudarsela/gateway
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: "development"
        - name: APP_PORT
          value: "5001"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30051
  selector:
    app: apollo-gateway
